This is the final fit that I decided to go with after a lot of exploring.

In [19]:
import pandas as pd
from sklearn import model_selection
from sklearn import linear_model
from sklearn import metrics
from sklearn import ensemble
from sklearn.utils import resample
from sklearn import svm
import numpy as np




In [20]:
#import NYC data and inspect
df = pd.read_pickle('Nydatafinal.pkl')

In [21]:
len(df)

388

In [22]:
#check imbalance
len(df[df.isbest])

20

In [23]:
df.head()

surveyOverallRatingScore  isbest  Number_pub  \
fullname                                                          
Sylvia Adams                           10.0   False        36.0   
Morton Coleman                         10.0   False        90.0   
Karen Haglof                            9.0   False         1.0   
Michael Grossbard                       7.0    True        39.0   
Jeffrey Tepler                         10.0   False         1.0   

                   HGST7FF97B36330214  HGST750A7B36330101  HGSTF40A7B36330154  \
fullname                                                                        
Sylvia Adams                      1.0                 0.0                 0.0   
Morton Coleman                    0.0                 1.0                 0.0   
Karen Haglof                      1.0                 0.0                 0.0   
Michael Grossbard                 1.0                 0.0                 0.0   
Jeffrey Tepler                    0.0                 1.0                 0.0   

                   HGST3A0A7B36330012  HGSTE10A7B36330204  HGST760A7B36330119  \
fullname                                                                        
Sylvia Adams                      0.0                 0.0                 0.0   
Morton Coleman                    0.0                 0.0                 0.0   
Karen Haglof                      0.0                 0.0                 0.0   
Michael Grossbard                 0.0                 0.0                 0.0   
Jeffrey Tepler                    0.0                 0.0                 0.0   

                   HGSTB00A7B36330236  \
fullname                                
Sylvia Adams                      0.0   
Morton Coleman                    0.0   
Karen Haglof                      0.0   
Michael Grossbard                 0.0   
Jeffrey Tepler                    0.0   

                                         ...                          \
fullname                                 ...                           
Sylvia Adams                             ...                           
Morton Coleman                           ...                           
Karen Haglof                             ...                           
Michael Grossbard                        ...                           
Jeffrey Tepler                           ...                           

                   HGSTA5380596310008  HGSTC6380596310025  HGST600A7B36330231  \
fullname                                                                        
Sylvia Adams                      0.0                 0.0                 0.0   
Morton Coleman                    0.0                 0.0                 0.0   
Karen Haglof                      0.0                 0.0                 0.0   
Michael Grossbard                 0.0                 0.0                 0.0   
Jeffrey Tepler                    0.0                 0.0                 0.0   

                   HGST11346F56140088  i10_score  totalcit  is_Rec  \
fullname                                                             
Sylvia Adams                      0.0         30    2195.0     1.0   
Morton Coleman                    0.0         77    4674.0     1.0   
Karen Haglof                      0.0          0       0.0     1.0   
Michael Grossbard                 0.0         29    1440.0     0.0   
Jeffrey Tepler                    0.0          1     144.0     1.0   

                   recent_pubs  trialcount  \
fullname                                     
Sylvia Adams                26           5   
Morton Coleman              41           8   
Karen Haglof                 1           0   
Michael Grossbard           17           1   
Jeffrey Tepler               0           0   

                                                        ArticleWords  
fullname                                                              
Sylvia Adams       NFS1 undergoes positive selection in lung tumo...  
Morton Coleman     A Phas

In [24]:
#normalize data

In [25]:
def normalizeseries(inputseries):
    mean = inputseries.mean()
    std = inputseries.std()
    return (inputseries-mean)/std

In [26]:
df.Number_pub = normalizeseries(df.Number_pub)
df.surveyOverallRatingScore = normalizeseries(df.surveyOverallRatingScore)
df.i10_score = normalizeseries(df.i10_score)
df.totalcit = normalizeseries(df.totalcit)
df.trialcount = normalizeseries(df.trialcount)

In [27]:
df.head()

surveyOverallRatingScore  isbest  Number_pub  \
fullname                                                          
Sylvia Adams                       1.187003   False    0.051205   
Morton Coleman                     1.187003   False    1.064283   
Karen Haglof                       0.962887   False   -0.605419   
Michael Grossbard                  0.514657    True    0.107487   
Jeffrey Tepler                     1.187003   False   -0.605419   

                   HGST7FF97B36330214  HGST750A7B36330101  HGSTF40A7B36330154  \
fullname                                                                        
Sylvia Adams                      1.0                 0.0                 0.0   
Morton Coleman                    0.0                 1.0                 0.0   
Karen Haglof                      1.0                 0.0                 0.0   
Michael Grossbard                 1.0                 0.0                 0.0   
Jeffrey Tepler                    0.0                 1.0                 0.0   

                   HGST3A0A7B36330012  HGSTE10A7B36330204  HGST760A7B36330119  \
fullname                                                                        
Sylvia Adams                      0.0                 0.0                 0.0   
Morton Coleman                    0.0                 0.0                 0.0   
Karen Haglof                      0.0                 0.0                 0.0   
Michael Grossbard                 0.0                 0.0                 0.0   
Jeffrey Tepler                    0.0                 0.0                 0.0   

                   HGSTB00A7B36330236  \
fullname                                
Sylvia Adams                      0.0   
Morton Coleman                    0.0   
Karen Haglof                      0.0   
Michael Grossbard                 0.0   
Jeffrey Tepler                    0.0   

                                         ...                          \
fullname                                 ...                           
Sylvia Adams                             ...                           
Morton Coleman                           ...                           
Karen Haglof                             ...                           
Michael Grossbard                        ...                           
Jeffrey Tepler                           ...                           

                   HGSTA5380596310008  HGSTC6380596310025  HGST600A7B36330231  \
fullname                                                                        
Sylvia Adams                      0.0                 0.0                 0.0   
Morton Coleman                    0.0                 0.0                 0.0   
Karen Haglof                      0.0                 0.0                 0.0   
Michael Grossbard                 0.0                 0.0                 0.0   
Jeffrey Tepler                    0.0                 0.0                 0.0   

                   HGST11346F56140088  i10_score  totalcit  is_Rec  \
fullname                                                             
Sylvia Adams                      0.0   0.240777  0.077306     1.0   
Morton Coleman                    0.0   1.469319  0.635185     1.0   
Karen Haglof                      0.0  -0.543399 -0.416660     1.0   
Michael Grossbard                 0.0   0.214638 -0.092600     0.0   
Jeffrey Tepler                    0.0  -0.517259 -0.384254     1.0   

                   recent_pubs  trialcount  \
fullname                                     
Sylvia Adams                26    0.343482   
Morton Coleman              41    0.838299   
Karen Haglof                 1   -0.481214   
Michael Grossbard           17   -0.316275   
Jeffrey Tepler               0   -0.481214   

                                                        ArticleWords  
fullname                                                              
Sylvia Adams       NFS1 undergoes positive selection in lung tumo...  
Morton Coleman     A Phas

In [29]:
#split into test and training
df_fit = df.drop(columns = ['ArticleWords'])
df_train, df_test = model_selection.train_test_split(df_fit, test_size=0.2,random_state = 5)

In [30]:
X_test = df_test.drop(columns = 'isbest')
y_test = df_test.isbest

In [31]:
#try 7 fold splits within training sets to fit model
kf = model_selection.KFold(n_splits=7,random_state = 4)
kf.get_n_splits(df_train)

7

In [32]:
def conf_mat(model,X,y):
    #returns confusion matrix for a model given X and y
    pred_y = model.predict(X)
    return metrics.confusion_matrix(y,pred_y)

In [33]:
def accuracy(model,X,y):
#returns accuracy score for a model given X and y
    pred_y = model.predict(X)
    return metrics.accuracy_score(y,pred_y)
    

In [34]:
#attempt a logistic regression, random forests and svm classifier
# at various points I printed some metrics of each to visualize

modellog = []
modelrf = []
modelsvm = []

for train_index, test_index in kf.split(df_train):
    df_train_i = df_train.iloc[train_index]
    df_test_i = df_train.iloc[test_index]
    df_minority = df_train_i[df_train_i.isbest==1]
    df_majority = df_train_i[df_train_i.isbest==0]
    # upsample minority to address balance
    nnew = len(df_majority)
    df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=nnew,    # to match majority class
                                 random_state=100) # reproducible results
    df_resampled = pd.concat([df_majority, df_minority_upsampled])
    y_train = df_resampled.isbest
    y_test_i = df_test_i.isbest
    X_train = df_resampled.drop('isbest',axis=1)
    X_test_i = df_test_i.drop('isbest',axis=1)
    model_log = linear_model.LogisticRegression().fit(X_train,y_train)
    modellog.append(accuracy(model_log,X_test_i,y_test_i))
    model_rfc = ensemble.RandomForestClassifier(random_state = 211).fit(X_train,y_train)
    modelrf.append(accuracy(model_rfc,X_test_i,y_test_i))
    model_svm = svm.SVC(kernel='linear', C=1).fit(X_train,y_train)
    modelsvm.append(accuracy(model_svm,X_test_i,y_test_i))

    

In [35]:
#check log reg
print(np.mean(modellog))
print(modellog)

0.851515151515
[0.8666666666666667, 0.8666666666666667, 0.79545454545454541, 0.84090909090909094, 0.90909090909090906, 0.86363636363636365, 0.81818181818181823]


In [36]:
#check random forests
print(np.mean(modelrf))
print(modelrf)

0.941847041847
[0.93333333333333335, 0.97777777777777775, 0.97727272727272729, 0.88636363636363635, 0.93181818181818177, 0.95454545454545459, 0.93181818181818177]


In [37]:
#check svm
print(np.mean(modelsvm))
print(modelsvm)

0.835209235209
[0.84444444444444444, 0.91111111111111109, 0.75, 0.81818181818181823, 0.86363636363636365, 0.86363636363636365, 0.79545454545454541]


After deliberation, it seems the average of 7 logistic regressions is the best way to go: random forests overfits. Since the "best" doctors is not necessarily 100% in our case. 

In [38]:
modellog = []
#actually fit 7 logistic regressions

for train_index, test_index in kf.split(df_train):
    df_train_i = df_train.iloc[train_index]
    df_test_i = df_train.iloc[test_index]
    df_minority = df_train_i[df_train_i.isbest==1]
    df_majority = df_train_i[df_train_i.isbest==0]
    # upsample minority
    nnew = len(df_majority)
    df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # sample with replacement
                                 n_samples=nnew,    # to match majority class
                                 random_state=100) # reproducible results
    df_resampled = pd.concat([df_majority, df_minority_upsampled])
    y_train = df_resampled.isbest
    y_test_i = df_test_i.isbest
    X_train = df_resampled.drop('isbest',axis=1)
    X_test_i = df_test_i.drop('isbest',axis=1)
    model_log = linear_model.LogisticRegression().fit(X_train,y_train)
    modellog.append(model_log)

In [39]:
def printmodelmetrics(model,X,y):
    pred_y = model.predict(X)
    print('confusion matrix')
    print(metrics.confusion_matrix(y,pred_y))
    print('f1 score')
    print(metrics.f1_score(y,pred_y))
    print('accuracy')
    print(metrics.accuracy_score(y,pred_y))
    return metrics.f1_score(y,pred_y)

In [40]:
#check performance on test set
accuracy_test = []
for model in modellog:
    print(conf_mat(model,X_test,y_test))
    accuracy_test.append(accuracy(model,X_test,y_test))
print(np.mean(accuracy_test))
print(np.std(accuracy_test))

[[66  8]
 [ 1  3]]
[[65  9]
 [ 1  3]]
[[64 10]
 [ 1  3]]
[[65  9]
 [ 1  3]]
[[66  8]
 [ 2  2]]
[[65  9]
 [ 2  2]]
[[68  6]
 [ 1  3]]
0.875457875458
0.0163814503846


In [41]:
#This is good because we want to minimize false negatives so as to provide patients with more options
#save file
import pickle
with open('LogRegModels.pkl', "wb") as f:
   pickle.dump(modellog, f)
